// This file is generated by icon spritesheet generator

export const iconNames = [
  "X",
  "Sun",
  "Moon",
  "Minus",
  "LoaderCircle",
  "Laptop",
  "Key",
  "Check",
] as const

export type IconName = typeof iconNames[number]
