// This file is generated by icon spritesheet generator

export const iconNames = [
  "Zap",
  "X",
  "Users",
  "Sun",
  "ShieldAlert",
  "Settings",
  "Settings2",
  "RefreshCw",
  "Plus",
  "Palette",
  "Moon",
  "Minus",
  "LoaderCircle",
  "Laptop",
  "Key",
  "Ellipsis",
  "EllipsisVertical",
  "Database",
  "ChevronRight",
  "Check",
  "Bookmark",
] as const

export type IconName = typeof iconNames[number]
